ww4_nodes:
  vars:
    ww4_node_profile: value-from-group-vars(yml)
  hosts:
    host3:
      ww4_node_profile: default
      ww4_node_hwaddr: 03:03:03:03:03:03
      int_ip_addr: 198.51.100.3
    host4:
      ww4_node_hwaddr: 04:04:04:04:04:04
      int_ip_addr: 198.51.100.4
      ww4_node_container: specific-container