---
# tasks file for ansible_role_deploy_ww4_nodes


- name: Print the node profiles delete commands to console
  ansible.builtin.debug:
    msg: "echo y |wwctl profile delete  {{item['Id']}}"
    verbosity: 1
  loop: "{{ ww4_profiles }}"

- name: Remove existing versions of the node profiles
  ansible.builtin.shell:
    cmd: "echo y |wwctl profile delete  {{item['Id']}}"
  loop: "{{ ww4_profiles }}"
  tags: notest
  ignore_errors: true  #It is ok if the profile doesn't exist yet.

- name: Print the node profiles creating commands to console
  ansible.builtin.debug:
    msg: "echo y | {{ lookup('ansible.builtin.template','profile_creation_command.j2') }}"
    verbosity: 1
  loop: "{{ ww4_profiles }}"

- name: Create the node profiles
  ansible.builtin.shell:
    cmd: "echo y | {{ lookup('ansible.builtin.template','profile_creation_command.j2') }}"
  loop: "{{ ww4_profiles }}"
  tags: notest

- name: Create temporary file for the .yml
  ansible.builtin.tempfile:
    state: file
    suffix: ".yml"
  register: tmp_for_yaml

- name: Write the compute node yaml file for importing
  ansible.builtin.template:
    src: templates/ww4_compute_nodes.yml.j2
    dest: "{{tmp_for_yaml.path}}"

- name: Save yaml file contents in a variable for debug
  ansible.builtin.command:
    cmd: "cat {{tmp_for_yaml.path}}"
  register: command_output
- name: Print yaml to console
  ansible.builtin.debug:
    msg: "{{command_output.stdout_lines}}"
    verbosity: 1

- name: Deploy the nodes in warewulf
  ansible.builtin.shell:
    cmd: "echo y |wwctl node import {{tmp_for_yaml.path}}"
  tags: notest

- name: Remove the temporary file
  ansible.builtin.file:
    path: "{{tmp_for_yaml.path}}"
    state: absent
  when: tmp_for_yaml.path is defined
  tags: notest
