---
# tasks file for ansible_role_deploy_ww4_nodes

- name: Create temporary folder for the .yml
  ansible.builtin.tempfile:
    state: directory
    suffix: container_storage
  register: tmp_folder_for_yaml

#- name: the nodes
#  ansible.builtin.debug:
#    msg: "node: {{ww4_node_hostname}} {{ww4_node_profile}} {{ww4_node_hwaddr}} {{ww4_node_ipaddr}}"
#  vars:
#    ww4_node_hostname: "{{item}}"
#    ww4_node_profile:  "{{hostvars[item|quote].ww4_node_profile    }}"
#    ww4_node_hwaddr:   "{{hostvars[item|quote].ww4_node_hwaddr     }}"
#    ww4_node_ipaddr:   "{{hostvars[item|quote].ww4_node_ipaddr     }}"
#  loop: "{{groups['ww4_nodes']}}"


- name: Write the compute node yaml file for importing
  ansible.builtin.template:
    src: templates/ww4_compute_nodes.yml.j2
    dest: "{{tmp_folder_for_yaml.path}}/ww4_compute_nodes.yml"
#  loop: "{{groups['ww4_nodes']}}"
#  vars:
#    ww4_node_hostname: "hostname"
#    ww4_node_profile:  "default"
#    ww4_node_hwaddr: "00:AA:00:00:99:99"
#    ww4_node_ipaddr: "198.51.100.1"


- name: yaml file contents
  ansible.builtin.command:
    cmd: "cat ww4_compute_nodes.yml"
    chdir: "{{tmp_folder_for_yaml.path}}"
  register: command_output
- name: Print to console
  ansible.builtin.debug:
    msg: "{{command_output.stdout_lines}}"


- name: Remove the temporary folder
  ansible.builtin.file:
    path: "{{tmp_folder_for_yaml.path}}"
    state: absent
  when: tmp_folder_for_yaml.path is defined
  tags: notest
