---
# tasks file for ansible_role_deploy_ww4_nodes

- name: Add overlays to warewulf4
  include_tasks: overlays.yml
  loop: "{{ ww4_overlays }}"
  loop_control:
    loop_var: overlay_item
  tags: ['overlays']

- name: Add node profiles to warewulf4
  include_tasks: profiles.yml
  loop: "{{ ww4_profiles }}"
  loop_control:
    loop_var: profile_item
  tags: ['profiles']

- name: Add nodes to warewulf4
  include_tasks: nodes.yml
  tags: ['nodes']


