---

- name: print files
  ansible.builtin.debug:
    msg: "{{file_item}}"
    verbosity: 2

- name: Add a templated file to overlay from the ansible role
  block:

  - name: Create temporary file
    ansible.builtin.tempfile:
      state: file
      suffix: overlayTemplate
    register: tmpFolderOverlayFile

  - name: Template the file to ww4 host
    ansible.builtin.template:
      src: "{{ file_item['ansible_src_template'] }}"
      dest: "{{ tmpFolderOverlayFile.path }}"
      owner: "{{ file_item['owner'] | default('root') }}"
      group: "{{ file_item['group'] | default('root') }}"
      mode: "{{ file_item['mode'] | default('400') }}"

  - name: Read Templated File Contents
    ansible.builtin.slurp:
      src: "{{ tmpFolderOverlayFile.path }}"
    register: file_content

  - name: Print the templated file
    ansible.builtin.debug:
      var: file_content.content | b64decode
      verbosity: 1

  - name: Add the file to ww4
    ansible.builtin.shell:
      cmd: "wwctl overlay import {{ overlay_item['name'] }} {{ tmpFolderOverlayFile.path }} {{ file_item['name'] }}"
    tags: notest

  - name: Remove temporary file
    ansible.builtin.file:
      path: "{{ tmpFolderOverlayFile.path }}"
      state: absent
    when: tmpFolderOverlayFile.path is defined



  when: file_item['ansible_src_template'] is defined
