---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    links:
      hosts: inventory/
#  group_vars:
#    ww4_nodes:
#      ww4_node_profile: 'very-default'
verifier:
  name: ansible
